### PR TITLE
add appveyor.yml

### PR DESCRIPTION
**Pull request by starius**
Based on https://github.com/oschwald/maxminddb-golang/blob/f4aa55714a3f843869ca9a38625e177a627c1ce6/appveyor.yml

I enabled the repo in AppVeyor and added `COVERALLS_TOKEN` to [AppVeyor's variables](https://ci.appveyor.com/project/starius/oniongateway/settings/environment).

### CODE REVIEW

**Comment by starius** [comment]
Ops, I added my fork.

**Comment by starius** [comment]
@DonnchaC 
AppVeyor adds my fork when I try to add your repo. Can you add it in AppVeyor, please?

**Comment by starius** [comment]
I switched off coveralls comments in pull requests in https://coveralls.io/github/DonnchaC/oniongateway/settings

**Comment by DonnchaC** [comment]
I've now added AppVeyor to this repo. Does it work for you now?

**Comment by starius** [comment]
It fails in goveralls

**Comment by starius** [comment]
@DonnchaC 
Have you set `COVERALLS_TOKEN` in https://ci.appveyor.com/project/DonnchaC/oniongateway/settings/environment ?

**Comment by DonnchaC** [comment]
Oh I missed that! Looks like the build on AppVeyor is passing now. Thanks!

**Pull request merged**
